### ISSUE TITLE
Crash on first run

### ISSUE THREAD

**Issue by johnkors** [JakeGinnivan/GitReleaseNotes#68]
Ran cinst gitreleasenotes

Typed Gitreleasenotes in a console from within my repo.

Crash.

Was expecting a /help thingy when running it without params..

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> Octokit.NotFoundException: repos/myorg/myprivaterepo/issues was not found.
   at Octokit.ApiPagination.<GetAllPages>d__1`1.MoveNext() in c:\Users\shiftkey\Documents\GitHub\octokit.net\Octokit\Clients\ApiPagination.cs:line 36
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at GitReleaseNotes.IssueTrackers.GitHub.GitHubIssueTracker.GetClosedIssues(Nullable`1 since) in c:\Users\jake.ginnivan\_code\GitReleaseNotes\src\GitReleaseNotes\IssueTrackers\GitHub\GitHubIssueTracker.cs:line 117
   at GitReleaseNotes.ReleaseNotesGenerator.GenerateReleaseNotes(IRepository gitRepo, IIssueTracker issueTracker, SemanticReleaseNotes previousReleaseNotes, String[] categories, TaggedCommit tagToStartFrom, ReleaseInfo currentReleaseInfo, String diffUrlFormat) in c:\Users\jake.ginnivan\_code\GitReleaseNotes\src\GitReleaseNotes\ReleaseNotesGenerator.cs:line 22
   at GitReleaseNotes.Program.GenerateReleaseNotes(String[] args) in c:\Users\jake.ginnivan\_code\GitReleaseNotes\src\GitReleaseNotes\Program.cs:line 114
   at GitReleaseNotes.Program.Main(String[] args) in c:\Users\jake.ginnivan\_code\GitReleaseNotes\src\GitReleaseNotes\Program.cs:line 30
```

**Comment by JakeGinnivan** [comment]
Hey, sorry things are not working.

It looks like it is a private repository which would be causing the crash. You will have to pass an auth token. 

There is a bunch of stuff I want to do around this project, I am just struggling to find the time. Appreciate you taking the time to report the issue. The idea is that it should just work when you run it, and errors like this should be caught and decent error messages given.
